// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4s9hi2j5CCVjqZVDG18x0CLnZyzvuLeY',
    appId: '1:856418603747:web:27d101ce97ee0a9b81abd6',
    messagingSenderId: '856418603747',
    projectId: 'eprobi-123',
    authDomain: 'eprobi-123.firebaseapp.com',
    storageBucket: 'eprobi-123.appspot.com',
    measurementId: 'G-BKRKB8KE3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRP4TLCKwMAswaoNo7nRCgrTiE-7Y3KhU',
    appId: '1:856418603747:android:cb630d2773aa488081abd6',
    messagingSenderId: '856418603747',
    projectId: 'eprobi-123',
    storageBucket: 'eprobi-123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAdxsKrhF-7f8manGbcA0FQ866TEQklx0',
    appId: '1:856418603747:ios:376a4b03c51b4dc281abd6',
    messagingSenderId: '856418603747',
    projectId: 'eprobi-123',
    storageBucket: 'eprobi-123.appspot.com',
    iosClientId: '856418603747-oc8jjgqcuegkku45cr4cb3s9jkb3n548.apps.googleusercontent.com',
    iosBundleId: 'com.yahoo.avriljeanmarc.eprobi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAdxsKrhF-7f8manGbcA0FQ866TEQklx0',
    appId: '1:856418603747:ios:376a4b03c51b4dc281abd6',
    messagingSenderId: '856418603747',
    projectId: 'eprobi-123',
    storageBucket: 'eprobi-123.appspot.com',
    iosClientId: '856418603747-oc8jjgqcuegkku45cr4cb3s9jkb3n548.apps.googleusercontent.com',
    iosBundleId: 'com.yahoo.avriljeanmarc.eprobi',
  );
}
